---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alex.
--- DateTime: 2023/6/28 15:23
---
require("mqttnet")
require("tcpnet")
function initDevice()
    --初始化gpio状态
    print("初始化gpio状态")
    gpio.setup(29, 0, gpio.PULLUP)
    gpio.setup(30, 0, gpio.PULLUP)
    gpio.setup(31, 0, gpio.PULLUP)

    -- 还没联网的gpio状态
    print("初始化还没联网的gpio状态")
    gpio.set(30, 1)
    gpio.set(29, 1)
    --优先设置使用外置卡
    print("优先设置使用外置卡")
    mobile.simid(2, true)
end

function initConfig()
    -- 开启数据库
    log.info("initConfig")
    if fdb.kvdb_init("env", "onchip_fdb") == false then
        log.error(PROJECT .. ".kvdb_init", "error")
        return false, false
    else
        --0:mqtt  1：tcp   2：mqcp
        local mode = fdb.kv_get("mode")
        print(mode)
        if mode then
            return mode, true
        else
            return false, true
        end

    end
end

function gpioLoop()
    --sys.timerLoopStart(function()
    --local net = subscribe("NET_STATUS_IND", function()
    --
    --end)
    while true do
        if mqttconnect or tcpConnect then
            if mobile.simid() == 0 then
                gpio.set(31, 1)
                sys.wait(900)
                gpio.set(31, 0)
                sys.wait(100)
            else
                gpio.set(31, 1)
                sys.wait(700)
                gpio.set(31, 0)
                sys.wait(100)
                gpio.set(31, 1)
                sys.wait(100)
                gpio.set(31, 0)
                sys.wait(100)
            end
        else
            sys.wait(200)
            gpio.toggle(31)
        end
    end
end
