---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alex.
--- DateTime: 2023/8/9 14:50
---
---
---
uartKeyWords = {
    baudRate = "baudRate",
    dataBit = "dataBit",
    stopBit = "stopBit",
    checkDigit = "checkDigit",
}

mqttKeyWords ={
    mqttUrl = "mqttUrl",
    mqttPort = "mqttPort",
    mqttSSL = "mqttSSL",
    clientId = "clientId",
    customClientId = "cusClientId",
    userName = "userName",
    passWord = "passWord",
    subscribeFor = "subFor",
    subscribeClient = "subClient",
    subscribeBk = "subBk",
    subscribeQos = "subQos",
    publishFor = "pubFor",
    publishClient = "pubClient",
    publishBk = "pubBk",
    publishQos = "pubQos",
}
tcpKeyWords = {
    tcpUrl = "tcpUrl",
    tcpPort = "tcpPort",
    tcpOrUdp = "tcpOrUdp",
    regType = "regType",
    regData = "regData",
    heartType = "heartType",
    heartData = "heartData",
    heartTime = "heartTime",
}