---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alex.
--- DateTime: 2023/6/28 15:15
---
PROJECT = "NET-LTE-DTU"
VERSION = "1.0.3"
PRODUCT_KEY = ""
log.info("main", PROJECT, VERSION)
_G.sys = require("sys")
_G.sysplus = require("sysplus")
require("init")
require("mqttmodule")
require("uartmodule")
require("tcpmodule")
require("testmodule")
local libfota = require("libfota")
--require("mqcpmodule")
log.style(2)


-- 判断wdt
if wdt then
    -- 添加硬狗防止程序卡死，在支持的设备上启用这个功能
    wdt.init(9000) -- 初始化watchdog设置为9s
    sys.timerLoopStart(wdt.feed, 3000) -- 3s喂一次狗
end
--升级功能，需要时自行放开  去合宙官网注册并将配置的PRODUCT_KEY填入上方
--function libfota_cb(result)
--    log.info("fota", "result", result)
--    -- fota成功
--
--    if result == 0 then
--        rtos.reboot()   --如果还有其他事情要做,就不要立刻reboot
--    end
--end

--检测升级，需要时自行放开
-- 联网后会发一次这个消息
--sys.subscribe("IP_READY", function(ip, adapter)
--    log.info("mobile", "IP_READY", ip, (adapter or -1) == socket.LWIP_GP)
--    sys.taskInit(function()
--        libfota.request(libfota_cb)
--    end)
--end)
--初始化必要流程
initDevice()

--gpio控制操作
sys.taskInit(gpioLoop)


--初始化数据库
local workMode, dbStatus = initConfig()
if dbStatus then
    log.info("main" .. "数据库初始化成功:")

    --初始化串口
    uartInitData = initUart()
end

if uartInitData then
    log.info("main" .. "串口初始化成功:" .. uartId)
end

--5是5500  1 是 sim卡,sim卡和5500网络状态注册监听
sys.subscribe("IP_READY", function(ip, adapter)
    log.info("ipready", ip, adapter)
    if adapter == 1 then
        is4GConnect = true
    elseif adapter == 5 then
        isW5500Connect = true
    end

end)

sys.subscribe("IP_LOSE", function(adapter)
    log.info("iplose", adapter)
    if adapter == 1 then
        is4GConnect = false
        pm.reboot()
    elseif adapter == 5 then
        isW5500Connect = false
        pm.reboot()
    end
end)

--初始化数据库和工作模式
sys.taskInit(function()
    repeat
        sys.wait(3000)
        local workMode, dbStatus = initConfig()

        if workMode and dbStatus then
            log.info("数据库初始化完成")
            print("配置数据正常", workMode, dbStatus)
            --1:mqtt-dtu  2：tcp-dtu   2：mqcp
            if workMode == 1 then
                log.info("运行MQTT-DTU模式")
                initMqttConfig()
            elseif workMode == 2 then
                log.info("TCP/DTU-DTU")
                initTcpConfig()
            end
        elseif workMode == false and dbStatus then
            log.info("未配置模式")
            initTestMqttConfig()
        else
            print("配置数据不正确", "workMode", workMode, "dbStatus", dbStatus)
        end
    until dbStatus
end)

sys.run()
