---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alex.
--- DateTime: 2023/7/6 16:37
---
require("tcpnet")
require("keyWord")

local tcpUrl = ""
local tcpPort = 1883
local tcpOrUdp = 1
local isUdp = true
local regData = ""
local regType = ""

local heartType = ""
local heartData = ""
local heartTime = 0

function initTcpConfig()
    tcpUrl = fdb.kv_get(tcpKeyWords.tcpUrl)
    tcpPort = fdb.kv_get(tcpKeyWords.tcpPort)
    tcpOrUdp = fdb.kv_get(tcpKeyWords.tcpOrUdp)

    isUdp = tonumber(tcpOrUdp) == 1 and true or false

    local dbRegType = fdb.kv_get(tcpKeyWords.regType)
    --1表示使用imei
    if tonumber(dbRegType) == 1 then
        regData = mobile.imei() == nil and "" or mobile.imei()
        print("mobile.imei()", mobile.imei())
        --2表示使用iccid
    elseif tonumber(dbRegType) == 2 then
        regData = mobile.iccid() == nil and "" or mobile.iccid()
        --3表示使用自定义数据
    elseif tonumber(dbRegType) == 3 then
        regData = fdb.kv_get(tcpKeyWords.regData) == nil and "" or fdb.kv_get(tcpKeyWords.regData)
    elseif tonumber(dbRegType) == 4 then
        regData = ""
    end

    local dbHeartType = fdb.kv_get(tcpKeyWords.heartType)
    --1表示使用imei
    if tonumber(dbHeartType) == 1 then
        heartData = mobile.imei() == nil and "" or mobile.imei()
        --2表示使用iccid
    elseif tonumber(dbHeartType) == 2 then
        heartData = mobile.iccid() == nil and "" or mobile.iccid()
        --3表示使用自定义数据
    elseif tonumber(dbHeartType) == 3 then
        heartData = fdb.kv_get(tcpKeyWords.heartData) == nil and "" or fdb.kv_get(tcpKeyWords.heartData)
    elseif tonumber(dbHeartType) == 4 then
        heartData = ""
    end

    heartTime = fdb.kv_get(tcpKeyWords.heartTime) == nil and 0 or tonumber(fdb.kv_get(tcpKeyWords.heartTime))
    if tcpUrl and tcpPort and tcpUrl ~= "" and tcpPort ~= "" then
        tcpConstruct(tcpUrl, tcpPort, isUdp, regData, heartData, heartTime)

        print(tcpUrl, tcpPort, isUdp, regData, heartData, heartTime)
    else
        log.info("TCP模式连接配置失败，tcpUrl and tcpPort 为空")
    end

end


-- 处理串口数据，分发
function handleUartToTcp(uartData)
    local dataString = uartData
    print("TCP模式接收到串口数据", dataString)

    if mNetc then
        socketSend(uartData)
    else
        log.info("TCP未连接")
    end

end