---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alex.
--- DateTime: 2023/8/22 10:31
---
local subscribe  = ""
local publish  = ""
function initTestMqttConfig()
    local imei = mobile.imei()
    if imei then
        subscribe = imei
        publish = imei
        initMqttConnect("broker.emqx.io", 1883, false, crypto.trng(5), nil, nil, imei, 0, imei, 0)

    end
end

-- 处理串口数据，分发
function handleUartToTestMqtt(uartData)

    print("测试MQTT模式接收到串口数据", uartData)

    if mqttc then
        print("发布主题", publish)
        mqttc:publish(publish, uartData, 0)
    else
        log.info("mqtt未连接")
    end

end